version: '3'
services:
  web:
    build: .
    command: python -u webpage_data_helper_tests.py
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.0.4
    logging:
      driver: 'none'